language: android
jdk: oraclejdk7
android:
    components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
script:
    - git fetch --unshallow
    - cp app/key.properties.sample app/key.properties
    - keytool -genkey -v -keystore app/debug.keystore -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 1 -storepass android -keypass android -dname "cn=TEST, ou=TEST, o=TEST, c=TE"
    - ./gradlew clean build
